### ISSUE TITLE
Wishlists

### ISSUE THREAD

**Issue by Code-Slave** [Code-Slave/LazylibrarianDocs#1]
need a general overview of thier function

**Comment by philborman** [comment]
Wishlists.
You want lazylibrarian to try to find all the books in the list.
Useful for things like New York Times Best Sellers or a goodreads shelf where users can add requested books, or copying someone else's ideas of books you might like (goodreads listopia collections)

You can choose whether to try and grab ebook or audio or both

Lazylibrarian checks the list regularly for new additions.

**Comment by Code-Slave** [comment]
Thats nice. Looking for ny times feed now to provide examples
